name: Docker Image CI Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t tempzaq123/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true tempzaq123/react-test npm test -- --coverage

      - name: build prod images
        run: |
          docker build -t tempzaq123/multi-client ./client
          docker build -t tempzaq123/multi-nginx ./nginx
          docker build -t tempzaq123/multi-server ./server
          docker build -t tempzaq123/multi-worker ./worker

      - name: push prod images
        run: |
          docker push tempzaq123/multi-client
          docker push tempzaq123/multi-nginx
          docker push tempzaq123/multi-server
          docker push tempzaq123/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react-practice
          environment_name: Dockerreactpractice-env
          existing_bucket_name: elasticbeanstalk-us-east-1-863749405046
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
